// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// futhark_entry_main_cpp
int32_t futhark_entry_main_cpp(int32_t a, int32_t b);
RcppExport SEXP _R_futhark_example_futhark_entry_main_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int32_t >::type a(aSEXP);
    Rcpp::traits::input_parameter< int32_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(futhark_entry_main_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _R_futhark_example_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_R_futhark_example_futhark_entry_main_cpp", (DL_FUNC) &_R_futhark_example_futhark_entry_main_cpp, 2},
    {"_R_futhark_example_rcpp_hello_world", (DL_FUNC) &_R_futhark_example_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_R_futhark_example(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
