# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call C function from Rcpp
#' @export
futhark_entry_main_cpp <- function(a, b) {
    .Call('_R_futhark_example_futhark_entry_main_cpp', PACKAGE = 'R.futhark.example', a, b)
}

